name: Build

on:
  workflow_dispatch:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore & Build
      run: msbuild /t:restore && msbuild /p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: GumpStudio
        path: Build
