name: Build

on:
  workflow_dispatch:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
            
    - name: Build
      # This uses msbuild, see https://github.com/dotnet/msbuild/issues/4704
      run: msbuild /property:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: GumpStudio
        path: Build/
